elev_cafe_max: 2000
elev_cafe_min: 600
lat_max: 5.7
lat_min: 4.7
lon_max: -74.9
lon_min: -76.2
test_start: '2022-01-01'
train_end: '2018-12-31'
ultima_actualizacion_datos: '2026-05-08'
ultima_actualizacion_pipeline: '2026-05-17'
umbral_nulos_pixel: 70
val_end: '2021-12-31'
val_start: '2019-01-01'
